### ISSUE TITLE
jackmeter fails to build with newest GNU ld

### ISSUE THREAD

**Issue by alessio** [njh/jackmeter#1]
Hi!

On Debian/Ubuntu we've applied the following patch to make jackmeter able to build with the newest GNU's linker:

Description: Fix build failure with binutils-gold.
Author: Alessio Treglia alessio@debian.org
## Forwarded:

 Makefile.am |    2 +-
 Makefile.in |    2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

--- jackmeter.orig/Makefile.am
+++ jackmeter/Makefile.am
@@ -1,7 +1,7 @@
 AUTOMAKE_OPTIONS = foreign

 AM_CFLAGS = -g -Wall @JACK_CFLAGS@
-AM_LDFLAGS = -lm @JACK_LIBS@
+LIBS = -lm @JACK_LIBS@

 bin_PROGRAMS = jack_meter
 jack_meter_SOURCES = jack_meter.c
--- jackmeter.orig/Makefile.in
+++ jackmeter/Makefile.in
@@ -109,7 +109,7 @@ target_alias = @target_alias@
 AUTOMAKE_OPTIONS = foreign

 AM_CFLAGS = -g -Wall @JACK_CFLAGS@
-AM_LDFLAGS = -lm @JACK_LIBS@
+LIBS = -lm @JACK_LIBS@

 bin_PROGRAMS = jack_meter
 jack_meter_SOURCES = jack_meter.c

I thought you might be interested in doing the same.

Cheers.

**Comment by njh** [comment]
Fixed in 71e627f90fcc50c42632e36a1df088ce6578404d.

Thanks!

**Comment by njh** [comment]
And just released version 0.4:
http://www.aelius.com/njh/jackmeter/jackmeter-0.4.tar.gz
